# 1단계: 빌드 스테이지
FROM node:22.15.0-alpine AS builder

WORKDIR /app

# package.json과 package-lock.json 복사
COPY package.json ./

# 의존성 설치
RUN npm install

# 소스 코드 복사
COPY . .

# 프로덕션 빌드
RUN npm run build

# 다단계 빌드.
FROM node:22.15.0-alpine AS runner

WORKDIR /app

# serve 설치
RUN npm install -g serve

# 빌드된 파일 복사
COPY --from=builder /app/dist ./dist

EXPOSE 20030

# 정적 파일 서빙
CMD ["serve", "-s", "dist", "-l", "20030"]
