version: '3.8'
services:
  anabada-frontend:
    container_name: anabada-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    networks:
      - dmoj_nginx_network
      - bada-network

    #dmoj_nginx_network 안에 nginx-gui-proxy dockernetwork가 포함되어 있습니다.

  anabada-middleware:
    container_name: anabada-middleware
    build:
      context: ./middleware
      dockerfile: Dockerfile

    ports:
      - "20050:80"

    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}

    networks:
      - dmoj_nginx_network
      - bada-network

  anabada-backend:
    container_name: anabada-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

    #PORT 불필요.. 내부에서 20031로 호스팅 하도록 합니다.
    #SSH 포트 터널링으로 테스트 할겸 열어만 두었습니다. 나중에 없애기...
    ports:
      - "20031:20031"

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

    networks:
      - dmoj_nginx_network
      - bada-network

    #dmoj_nginx_network 안에 nginx-gui-proxy dockernetwork가 포함되어 있습니다.

networks:
  dmoj_nginx_network:
    external: true
  bada-network:
    external: true
  
