services:
  anabada-frontend:
    container_name: anabada-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    # volumes:
    #   - ./frontend:/app

    #dmoj_nginx_network 안에 nginx-gui-proxy dockernetwork가 포함되어 있습니다.

  anabada-middleware:
    container_name: anabada-middleware
    build:
      context: ./middleware
      dockerfile: Dockerfile

    # ports:
    #   - "20030:80"

    environment:
      - PORT=${PORT}
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}

  anabada-backend:
    container_name: anabada-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

    #PORT 불필요.. 내부에서 20031로 호스팅 하도록 합니다.
    #SSH 포트 터널링으로 테스트 할겸 열어만 두었습니다. 나중에 없애기...
    # ports:
    #   - "20031:3000"

    environment:
      - DB_HOST=localhost
      - DB_PORT=20040
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}

  

    #dmoj_nginx_network 안에 nginx-gui-proxy dockernetwork가 포함되어 있습니다.
  bada-nginx:
    image: nginx:latest

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "20050:80"

    depends_on:
      - anabada-backend
      - anabada-middleware
