services:
  anabada-frontend:
    container_name: anabada-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    networks:
      - bada-network

    environment:
      - NODE_ENV=production
      - BACKEND_URL=https://bada.anacnu.kr/

  anabada-middleware:
    container_name: anabada-middleware
    build:
      context: ./middleware
      dockerfile: Dockerfile

    # ports:
    #   - "20030:80"

    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - ALLOWED_ORIGIN=https://bada.anacnu.kr
    networks:
      - bada-network

  anabada-backend:
    container_name: anabada-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

    #PORT 불필요.. 내부에서 20031로 호스팅 하도록 합니다.
    #PORT 20031로 직접 접근하면 안됩니다. 나중에 막습니다.
    # ports:
    #   - "20031:3000"

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=production
      - ALLOWED_ORIGIN=https://bada.anacnu.kr
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}

    networks:
      - bada-network

    restart: unless-stopped

    #dmoj_nginx_network 안에 nginx-gui-proxy dockernetwork가 포함되어 있습니다.

  bada-nginx:
    image: nginx:latest

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "20050:80"
    networks:
      - dmoj_nginx_network
      - bada-network

    depends_on:
      - anabada-backend
      - anabada-middleware
  
  anabada-mysql:
    image: mysql:latest
    container_name: anabada-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - '20040:3306'

    volumes:
      - ./database/mysql_data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      # dump 폴더안에, dump 파일들을 넣어놓으면, 컨테이너 실행시 최초 실행한다.
      - ./database/dump:/docker-entrypoint-initdb.d  

    networks:
      - bada-network

  # anabada-crawling:
  #   container_name: anabada-crawling
  #   build:
  #     context: ./crawling
  #     dockerfile: Dockerfile
  #   networks:
  #     - bada-network

  #   env_file:
  #     - .env.bot

networks:
  dmoj_nginx_network:
    external: true
  bada-network:
    external: true
  
