name: Simple Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY}}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          cd /home/bada/apps/anabada/anabada-new
          git checkout main
          git pull origin main
          docker compose -f docker-compose.prod.yaml down
          docker compose -f docker-compose.prod.yaml up -d --build
