name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Clone or update repo on server
        run: |
          ssh -p ${{ secrets.DEPLOY_PORT }} -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd /home/ana/Desktop/ana/anabada-new
            git pull
          EOF

      - name: Deploy via SSH
        run: |
          ssh -p ${{ secrets.DEPLOY_PORT }} -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd /home/ana/Desktop/ana/anabada-new
            docker-compose -f docker-compose.prod.yaml down
            docker-compose -f docker-compose.prod.yaml build --no-cache
            docker-compose -f docker-compose.prod.yaml up -d
          EOF 